### ISSUE TITLE
SCTP transport

### ISSUE THREAD

**Issue by OrlandoST** [heimiricmr/bromelia#11]
Are there any plans for implementation SCTP transport for Bromelia?

**Comment by ptitdoc** [comment]
Hi, I have a working commit with SCTP on the first version of bromelia if you are interrested. I have to rework it to merge it to the main branch but I will try to do a push request during coming weeks

**Comment by ptitdoc** [comment]
https://github.com/heimiricmr/bromelia/pull/13

**Comment by heimiricmr** [comment]
Hi @OrlandoST. I've just pushed a squashed commit with @ptitdoc's contributions in the pull request mentioned above #13. Check it out: [5af44c2](https://github.com/heimiricmr/bromelia/commit/5af44c25de159733133e4f09b90c1852d95d5120)

**Comment by OrlandoST** [comment]
> Hi @OrlandoST. I've just pushed a squashed commit with @ptitdoc's contributions in the pull request mentioned above #13. Check it out: [5af44c2](https://github.com/heimiricmr/bromelia/commit/5af44c25de159733133e4f09b90c1852d95d5120)

Its a good news, thank you!
